[versions]
agp = "8.13.1"
kotlin = "1.9.25"
appcompat = "1.7.1"
autodispose = "2.1.1"
conductor = "2.1.5"
constraintlayout = "1.1.3"
dagger = "2.51"
datashare = "1.3.0"
documentfile = "1.0.1"
emoji2-bundled = "1.4.0"
exifinterface = "1.0.0"
exoplayer-core = "r2.9.0"
flexbox = "3.0.0"
glide = "4.16.0"
javax-annotation-api = "1.3.2"
junit = "4.12"
kotlinx-coroutines-core = "1.8.0"
kotlinx-coroutines-rx3 = "1.8.0"
ktx = "1.10.1"
libphonenumber-android = "8.13.47"
lifecycle-extensions = "2.2.0"
lifecycle-runtime-ktx = "2.7.0"
material = "1.13.0"
mockito-android = "2.18.3"
moshi = "1.8.0"
okhttp = "2.5.0"
okhttp-version = "4.10.0"
photoview = "2.1.4"
realm-android-adapters = "3.1.0"
realm-annotations = "10.19.0"
robolectric = "4.10.3"
runner = "1.1.0-alpha3"
rxandroid = "3.0.2"
rxbinding3 = "4.0.0"
rxjava = "3.1.8"
rxkotlin = "3.0.1"
shortcutbadger = "1.1.22"
timber = "5.0.1"
google-services = "4.3.14"
viewpager2 = "1.0.0-beta05"
work-runtime-ktx = "2.8.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
androidx-emoji2-bundled = { module = "androidx.emoji2:emoji2-bundled", version.ref = "emoji2-bundled" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle-extensions" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-extensions" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime-ktx" }
autodispose = { module = "com.uber.autodispose2:autodispose", version.ref = "autodispose" }
autodispose-android = { module = "com.uber.autodispose2:autodispose-android", version.ref = "autodispose" }
autodispose-androidx-lifecycle = { module = "com.uber.autodispose2:autodispose-androidx-lifecycle", version.ref = "autodispose" }
autodispose-androidx-lifecycle-test = { module = "com.uber.autodispose2:autodispose-androidx-lifecycle-test", version.ref = "autodispose" }
autodispose-lifecycle = { module = "com.uber.autodispose2:autodispose-lifecycle", version.ref = "autodispose" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
conductor = { module = "com.bluelinelabs:conductor", version.ref = "conductor" }
conductor-archlifecycle = { module = "com.bluelinelabs:conductor-archlifecycle", version.ref = "conductor" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-android-processor = { module = "com.google.dagger:dagger-android-processor", version.ref = "dagger" }
dagger-android-support = { module = "com.google.dagger:dagger-android-support", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
datashare = { module = "com.callcontrol:datashare", version.ref = "datashare" }
exoplayer-core = { module = "com.github.google.ExoPlayer:exoplayer-core", version.ref = "exoplayer-core" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
javax-annotation-api = { module = "javax.annotation:javax.annotation-api", version.ref = "javax-annotation-api" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-reactive = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactive", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-rx3 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx3", version.ref = "kotlinx-coroutines-rx3" }
libphonenumber-android = { module = "io.michaelrocks:libphonenumber-android", version.ref = "libphonenumber-android" }
material = { module = "com.google.android.material:material", version.ref = "material" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockito-android" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-android" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
okhttp = { module = "com.squareup.okhttp:okhttp", version.ref = "okhttp" }
okhttp-urlconnection = { module = "com.squareup.okhttp:okhttp-urlconnection", version.ref = "okhttp" }
okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp-version" }
photoview = { module = "com.github.chrisbanes:photoview", version.ref = "photoview" }
realm-android-adapters = { module = "com.github.realm:realm-android-adapters", version.ref = "realm-android-adapters" }
realm-android-library = { module = "io.realm:realm-android-library", version.ref = "realm-annotations" }
realm-annotations-processor = { module = "io.realm:realm-annotations-processor", version.ref = "realm-annotations" }
rxandroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid" }
rxbinding3 = { module = "com.jakewharton.rxbinding4:rxbinding", version.ref = "rxbinding3" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }
rxkotlin = { module = "io.reactivex.rxjava3:rxkotlin", version.ref = "rxkotlin" }
shortcutbadger = { module = "me.leolin:ShortcutBadger", version.ref = "shortcutbadger" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Tests
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
junit = { module = "junit:junit", version.ref = "junit" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
